# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWqeZqIUVKGRGdIbzrXU9QFgucKnA6Q4
"""

# -*- coding: utf-8 -*-
"""app.py"""

import streamlit as st

# Page config
st.set_page_config(
    page_title="Welcome to SWISS",
    page_icon="💊",
    layout="centered"
)

# Style
st.markdown("""
    <style>
        body {
            background: linear-gradient(to right, #f9fcff, #e0ecf5);
        }
        .title {
            font-size: 42px;
            font-weight: 800;
            color: #2c3e50;
            text-align: center;
        }
        .subtitle {
            font-size: 18px;
            color: #34495e;
            text-align: center;
            margin-top: 10px;
        }
        .card {
            background-color: #ffffff;
            padding: 2rem;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.06);
            margin-top: 2rem;
        }
    </style>
""", unsafe_allow_html=True)

# Title
st.markdown("<div class='title'>👋 Welcome to <span style='color:#2980b9'>SWISS</span></div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Your Smart Production Scheduling Platform</div>", unsafe_allow_html=True)

# Info Card
st.markdown("""
    <div class="card">
        <p style="font-size: 17px; color: #333;">
            Use the sidebar to access different modules:
        </p>
        <ul style='font-size:16px; line-height:1.6'>
            <li>💉 <b>Ampoule Scheduler</b> – Plan production for ampoule lines with overrideable speed settings.</li>
            <li>🧪 <b>Vial Scheduler</b> – Schedule batches for vials with type-aware speed control (e.g., 2m vs 2t).</li>
            <li>📊 <b>Production Dashboard</b> – View daily performance metrics, KPIs, and trends across both lines. No upload needed!</li>
            <li>📦 <b>OTIF Analysis</b> – Upload your P.O. data to calculate On-Time, In-Full, and OTIF performance, plus monthly summaries and vendor insights.</li>
        </ul>
    </div>
""", unsafe_allow_html=True)

# Image
st.image("https://images.unsplash.com/photo-1581090700227-1e8a5c160c4f", use_container_width=True)